### ISSUE TITLE
Univariate Analysis

### ISSUE THREAD

**Issue by vikashg** [sulantha2006/VoxelStats#2]
I do not know if this is really an issue. However, I was wondering if it is possible somehow to do a univariate analysis too using VoxelStats. Basically, we are hoping that if so is the case a good univariate vs multivariate comparative study can be done .

**Comment by sulantha2006** [comment]
Hi, Yes, A univariate analysis can easily be done with VoxelStats. Say your independent variable is X and the response variable is Y, then you can easily run the model 'Y~X' in VoxelStats. However, if you want to compare this with say 'Y~X+Z', you have to do it separately. With the next update, I will add the functionality to get the R^2 values and the AIC (for some), so that you can compare. 
Again, these are done per voxel basis. So the comparison needs to be per voxel basis.
